# Generated by Django 4.1.1 on 2022-11-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_event_allevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allevent',
            name='event_date',
            field=models.IntegerField(),
        ),
    ]
