# Generated by Django 4.1.1 on 2022-11-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_allevent_event_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='allevent',
            name='seat_price',
            field=models.IntegerField(default=0),
        ),
    ]
