# Generated by Django 4.1.1 on 2022-11-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_events_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='AllEvent',
        ),
    ]
