# Generated by Django 4.1.1 on 2022-11-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_allevent_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='allevent',
            name='event_place',
            field=models.CharField(default='', max_length=100),
        ),
    ]
